# -*- coding: utf-8 -*-
"""Chap01_Cm-01-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Hgw4jahNCoo5-Va974hszP4ieVnTF4w
"""

def prime_number(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
          #余りが0
            return False
    return True

# 1以上10以下の範囲に絞る
for i in range(1, 11):
    if prime_number(i):
        print(i)

def prime(N):
    prime = []
    for a in range(2, N):
        for b in range(2, int(N**0.5)+1):
            if a % b == 0:
                break
        else:
            prime.append(a)
    return prime
prime(70)